### ISSUE TITLE
整理

### ISSUE THREAD

**Issue by fs7744** [fs7744/Tars.Csharp#1]
0. 如下附件简单整理tars 包含的功能
[Tars.csharp.zip](https://github.com/fs7744/Tars.Csharp/files/2286748/Tars.csharp.zip)

1. csharp 已具有同步形式的 async/await
所以个人觉得不必考虑阻塞式实现方式，纯异步非阻塞多好

2. client 可采用aop框架生成代理类，用TaskCompletionSource + callback 记录表 支持async/await

3. callback 记录表 可用 ConcurrentDictionary 实现
暂时没有想到还有什么数据结构更适合这个

4. AspectCore-Framework aop 框架 功能非常强大
但是rpc的话，有个问题，无法区分 service 和 client 的代理， 这个需要研究下方法 

5. 之前做demo的时候，感觉 tars编码实现有地方还有优化
比如：减少中间byte数组创建

6. log 功能可以 基于Microsoft.Extensions.Logger 扩展 tars logger LogF.tars

7. config 功能 基于Microsoft.Extensions.Config 扩展 tars config  ConfigF.tars

8. 先基于 https://github.com/Azure/DotNetty 完整实现tcp所有功能后，我们再考虑其他内容哇

9. 找一个统一的地方列举以及讨论问题以及issue

**Comment by ElderJames** [comment]
第4点，服务端不代理，而是用一个调度器绑定实现方法
https://github.com/Shriek-Projects/shriek-fx/blob/master/src/Shriek.ServiceProxy.Socket/Core/ApiAction.cs 这个类用来缓存方法，当接受到对应类型的消息时，就能执行对应的方法

**Comment by fs7744** [comment]
4  有service 实现，我觉得让使用者直接调用本地实现就好，本来本地就有方法，再中间加处理感觉有点多余了
